blank_issues_enabled: false
contact_links:
- name: 💬 Janus Community (Discourse)
  url: https://janus.discourse.group/
  about: Please ask questions or discuss runtime problems on the group, not GitHub
